[postgres]
host = "dpg-crsmpjm8ii6s73ef126g-a.oregon-postgres.render.com"  # Replace with your Render PostgreSQL host
port = "5432"                                                  # Default PostgreSQL port
database = "finalyear_5mcn"                                   # Replace with your database name
username = "finalyear_5mcn_user"                             # Replace with your PostgreSQL username
password = "yknIT6Un2S8EroArfttd0OSNKStizj2B"                # Replace with your PostgreSQL password
